[package]
name = "codingame-spring-challenge-2021"
version = "0.1.0"
authors = ["ntk <43851479+ntk-ta01@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
